swagger: "2.0"
info:
  version: development
  description: todo
  title: todo
host: "???"
basePath: /
schemes:
  - http
  - https
paths:
  /todos:
    get:
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              todos:
                type: array
                items:
                  $ref: '#/definitions/Todo'
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: todo
          required: true
          description: todo information
          schema:
            $ref: '#/definitions/TodoRequest'
      responses:
        200:
          description: todo created
          schema:
            $ref: '#/definitions/Todo'
        400:
          description: invalid request body
        500:
          description: insertion failed
  /todos/{id}:
    get:
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: todo id
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Todo'
        404:
          description: not found
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: todo id
        - in: body
          name: todo
          required: true
          description: todo information
          schema:
            $ref: '#/definitions/TodoRequest'
      responses:
        200:
          description: todo updated
          schema:
            $ref: '#/definitions/Todo'
        400:
          description: invalid request body
        404:
          description: not found
        500:
          description: insertion failed
    delete:
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: todo id
      responses:
        200:
          description: todo updated
          schema:
            $ref: '#/definitions/Todo'
        404:
          description: not found
        500:
          description: insertion failed

definitions:
  TodoRequest:
    type: object
    properties: &todoBaseProperties
      task:
        type: string
      deadline:
        type: string
        format: date

  Todo:
    type: object
    properties:
      id:
        type: integer
      <<: *todoBaseProperties
